// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.107.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List recent blog posts on FranchiseLeadsPro (title, slug, published status, created date). Newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max posts to return (default 10)."),
    publishedOnly: z.boolean().optional().describe("Only return published posts (default false).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, publishedOnly }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("blog_posts").select("id,title,slug,is_published,published_at,created_at,author_name,excerpt").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (publishedOnly) q = q.eq("is_published", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-blog-posts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.107.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_blog_posts_default = defineTool2({
  name: "search_blog_posts",
  title: "Search blog posts",
  description: "Search FranchiseLeadsPro blog posts by keyword across title, excerpt, and content.",
  inputSchema: {
    query: z2.string().min(1).describe("Search text."),
    limit: z2.number().int().min(1).max(25).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const q = query.replace(/[%,]/g, " ");
    const { data, error } = await sb.from("blog_posts").select("id,title,slug,excerpt,is_published,published_at,created_at").or(`title.ilike.%${q}%,excerpt.ilike.%${q}%,content.ilike.%${q}%`).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-contact-submissions.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.107.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_contact_submissions_default = defineTool3({
  name: "list_contact_submissions",
  title: "List contact submissions (leads)",
  description: "List recent leads submitted via the contact form and franchise concern box. Admin-only via RLS.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max leads to return (default 10)."),
    status: z3.string().optional().describe("Filter by status (e.g. 'new', 'contacted').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let q = sb.from("contact_submissions").select("id,first_name,last_name,email,phone,company,role,service_interest,message,status,created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-chat-conversations.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.107.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_chat_conversations_default = defineTool4({
  name: "list_chat_conversations",
  title: "List chat conversations",
  description: "List recent visitor chat conversations from the site chat widget. Admin-only via RLS.",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).optional().describe("Max conversations to return (default 10)."),
    includeMessages: z4.boolean().optional().describe("Include messages for each conversation (default false).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, includeMessages }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const { data: convos, error } = await sb.from("chat_conversations").select("id,visitor_name,visitor_email,status,created_at,updated_at,ended_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let result = convos ?? [];
    if (includeMessages && convos && convos.length) {
      const ids = convos.map((c) => c.id);
      const { data: msgs } = await sb.from("chat_messages").select("id,conversation_id,sender_type,message,created_at").in("conversation_id", ids).order("created_at", { ascending: true });
      const byConvo = {};
      (msgs ?? []).forEach((m) => {
        (byConvo[m.conversation_id] ||= []).push(m);
      });
      result = convos.map((c) => ({ ...c, messages: byConvo[c.id] ?? [] }));
    }
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { conversations: result }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yquuidpajigvecyonqir";
var mcp_default = defineMcp({
  name: "franchiseleadspro-mcp",
  title: "FranchiseLeadsPro MCP",
  version: "0.1.0",
  instructions: "Tools for the FranchiseLeadsPro admin: list and search blog posts, view leads submitted via the contact/concern forms, and review visitor chat conversations. All tools act as the signed-in user and are governed by the site's row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_blog_posts_default, search_blog_posts_default, list_contact_submissions_default, list_chat_conversations_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
